#+ summary: Count the number of features annotated as aspidosperma type alkaloids by CANOPUS (p>0.5) in the different samples
#+ description: Count the number of features annotated as aspidosperma type alkaloids by CANOPUS (p>0.5) in the different samples
#+ endpoint: https://enpkg.commons-lab.org/graphdb/repositories/ENPKG
#+ tags:
#+   - ENPKG
#+   - Templated
#+ enumerate:
#+   - NPCClass:
#+     - https://enpkg.commons-lab.org/kg/npc_12_oxophytodienoic_acid_metabolites
#+     - https://enpkg.commons-lab.org/kg/npc_2_arylbenzofurans
#+     - https://enpkg.commons-lab.org/kg/npc_2_pyrone_derivatives
#+     - https://enpkg.commons-lab.org/kg/npc_3_Decalinoyltetramic_acids
#+     - https://enpkg.commons-lab.org/kg/npc_3_Spirotetramic_acids
#+     - https://enpkg.commons-lab.org/kg/npc_3_acyl_tetramic_acids
#+     - https://enpkg.commons-lab.org/kg/npc_3_oligoenoyltetramic_acids
#+     - https://enpkg.commons-lab.org/kg/npc_4_pyrone_derivatives
#+     - https://enpkg.commons-lab.org/kg/npc_Abeoabietane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Abeolupane_triterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Abeotaxane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Abietane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Acetate_derived_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Acetogenins
#+     - https://enpkg.commons-lab.org/kg/npc_Acidic_glycosphingolipids
#+     - https://enpkg.commons-lab.org/kg/npc_Acorane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Acridone_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Actinomycins
#+     - https://enpkg.commons-lab.org/kg/npc_Acutumine_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Acyclic_guanidine_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Acyclic_monoterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Acyclic_triterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Acyl_phloroglucinols
#+     - https://enpkg.commons-lab.org/kg/npc_Adianane_triterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Aeruginosins
#+     - https://enpkg.commons-lab.org/kg/npc_Aflatoxins
#+     - https://enpkg.commons-lab.org/kg/npc_Africanane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Agarofuran_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Ahp_containing_cyclodepsipeptides
#+     - https://enpkg.commons-lab.org/kg/npc_Alliacane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Allohimachalane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Amarylidaceae_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Amino_cyclitols
#+     - https://enpkg.commons-lab.org/kg/npc_Amino_fatty_acids
#+     - https://enpkg.commons-lab.org/kg/npc_Aminoacids
#+     - https://enpkg.commons-lab.org/kg/npc_Aminoglycosides
#+     - https://enpkg.commons-lab.org/kg/npc_Aminosugars
#+     - https://enpkg.commons-lab.org/kg/npc_Amphilectane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Anabaenopeptins
#+     - https://enpkg.commons-lab.org/kg/npc_Androstane_steroids
#+     - https://enpkg.commons-lab.org/kg/npc_Angucyclines
#+     - https://enpkg.commons-lab.org/kg/npc_Ansa_macrolides
#+     - https://enpkg.commons-lab.org/kg/npc_Ansa_peptide_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Anthocyanidins
#+     - https://enpkg.commons-lab.org/kg/npc_Anthracyclines
#+     - https://enpkg.commons-lab.org/kg/npc_Anthranillic_acid_derivatives
#+     - https://enpkg.commons-lab.org/kg/npc_Anthraquinones_and_anthrones
#+     - https://enpkg.commons-lab.org/kg/npc_Antimycins
#+     - https://enpkg.commons-lab.org/kg/npc_Aphidicolane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Aplysiatoxins
#+     - https://enpkg.commons-lab.org/kg/npc_ApocarotenoidsIu_
#+     - https://enpkg.commons-lab.org/kg/npc_Apocarotenoids_C30,_Y_Y
#+     - https://enpkg.commons-lab.org/kg/npc_Apocarotenoids_I¨_
#+     - https://enpkg.commons-lab.org/kg/npc_Apocarotenoids_I2_
#+     - https://enpkg.commons-lab.org/kg/npc_Apocarotenoids_Y_
#+     - https://enpkg.commons-lab.org/kg/npc_Apocarotenoids_b_
#+     - https://enpkg.commons-lab.org/kg/npc_Apocarotenoidse_
#+     - https://enpkg.commons-lab.org/kg/npc_Aporphine_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Apotirucallane_triterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Aristolane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Aromadendrane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Aromatic_polyketides_with_side_chains
#+     - https://enpkg.commons-lab.org/kg/npc_Arteminisin
#+     - https://enpkg.commons-lab.org/kg/npc_Arylnaphthalene_and_aryltetralin_lignans
#+     - https://enpkg.commons-lab.org/kg/npc_Asbestinane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Ascarosides
#+     - https://enpkg.commons-lab.org/kg/npc_Ascomycins_and_Rapamycins
#+     - https://enpkg.commons-lab.org/kg/npc_Asperane_sesterterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Aspidosperma_Iboga_hybrid_type_Vinca_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Aspidosperma_type
#+     - https://enpkg.commons-lab.org/kg/npc_Asteriscane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Atisane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Aurones
#+     - https://enpkg.commons-lab.org/kg/npc_Avermectins
#+     - https://enpkg.commons-lab.org/kg/npc_Azaphilones
#+     - https://enpkg.commons-lab.org/kg/npc_Azo_and_Azoxy_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Baccharane_triterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Bactoprenols
#+     - https://enpkg.commons-lab.org/kg/npc_Bafilomycins
#+     - https://enpkg.commons-lab.org/kg/npc_Bagremycins
#+     - https://enpkg.commons-lab.org/kg/npc_Bauerane_triterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Benastatins_and_derivatives
#+     - https://enpkg.commons-lab.org/kg/npc_Benzodiazepine_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Benzophenones
#+     - https://enpkg.commons-lab.org/kg/npc_Benzoquinones
#+     - https://enpkg.commons-lab.org/kg/npc_Bergamotane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Betaestacin_type_sesterterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Betalain_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Beyerane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Biaryl_type_diarylheptanoids
#+     - https://enpkg.commons-lab.org/kg/npc_Bicyclic_guanidine_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Bicyclogermacrane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Bicyclohumulane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Bisabolane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Bisnaphthalenes
#+     - https://enpkg.commons-lab.org/kg/npc_Boromycins
#+     - https://enpkg.commons-lab.org/kg/npc_Botryane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Bourbonane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Branched_fatty_acids
#+     - https://enpkg.commons-lab.org/kg/npc_Brasilane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Breviane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Briarane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Bryostatins
#+     - https://enpkg.commons-lab.org/kg/npc_Bufadienolides
#+     - https://enpkg.commons-lab.org/kg/npc_CDP_Glycerols
#+     - https://enpkg.commons-lab.org/kg/npc_Cadinane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Camphane_monoterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Campherenane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Cannabinoids
#+     - https://enpkg.commons-lab.org/kg/npc_Capnellane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Capsaicins_and_Capsaicinoids
#+     - https://enpkg.commons-lab.org/kg/npc_Carabrane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Carane_monoterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Carbapenems
#+     - https://enpkg.commons-lab.org/kg/npc_Carbazole_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Carbocyclic_fatty_acids
#+     - https://enpkg.commons-lab.org/kg/npc_Carboline_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Cardenolides
#+     - https://enpkg.commons-lab.org/kg/npc_Carotenoids_C40,_Ï€_Ï€
#+     - https://enpkg.commons-lab.org/kg/npc_Carotenoids_C40,_Ï€_I§
#+     - https://enpkg.commons-lab.org/kg/npc_Carotenoids_C40,_I¨_I¨
#+     - https://enpkg.commons-lab.org/kg/npc_Carotenoids_C40,_I³_I¨
#+     - https://enpkg.commons-lab.org/kg/npc_Carotenoids_C40,_I2_I§
#+     - https://enpkg.commons-lab.org/kg/npc_Carotenoids_C40,_I2_I¨
#+     - https://enpkg.commons-lab.org/kg/npc_Carotenoids_C40,_I2_Iº
#+     - https://enpkg.commons-lab.org/kg/npc_Carotenoids_C40,_I2_I2
#+     - https://enpkg.commons-lab.org/kg/npc_Carotenoids_C40,_I2_Iu
#+     - https://enpkg.commons-lab.org/kg/npc_Carotenoids_C40,_Q_Y
#+     - https://enpkg.commons-lab.org/kg/npc_Carotenoids_C40,_Y_Y
#+     - https://enpkg.commons-lab.org/kg/npc_Carotenoids_C40,_b_Q
#+     - https://enpkg.commons-lab.org/kg/npc_Carotenoids_C40,_b_Y
#+     - https://enpkg.commons-lab.org/kg/npc_Carotenoids_C40,_b_b
#+     - https://enpkg.commons-lab.org/kg/npc_Carotenoids_C40,_b_e
#+     - https://enpkg.commons-lab.org/kg/npc_Carotenoids_C40,_b_g
#+     - https://enpkg.commons-lab.org/kg/npc_Carotenoids_C40,_b_k
#+     - https://enpkg.commons-lab.org/kg/npc_Carotenoids_C40,_b_p
#+     - https://enpkg.commons-lab.org/kg/npc_Carotenoids_C40,_e_Y
#+     - https://enpkg.commons-lab.org/kg/npc_Carotenoids_C40,_g_Y
#+     - https://enpkg.commons-lab.org/kg/npc_Carotenoids_C40,_g_e
#+     - https://enpkg.commons-lab.org/kg/npc_Carotenoids_C40,_k_k
#+     - https://enpkg.commons-lab.org/kg/npc_Carotenoids_C40,_p_Y
#+     - https://enpkg.commons-lab.org/kg/npc_Carotenoids_C40,_p_p
#+     - https://enpkg.commons-lab.org/kg/npc_Carotenoids_C45,_b_Y
#+     - https://enpkg.commons-lab.org/kg/npc_Carotenoids_C50,_I¨_I¨
#+     - https://enpkg.commons-lab.org/kg/npc_Carotenoids_C50,_Iu_Iu
#+     - https://enpkg.commons-lab.org/kg/npc_Carotenoids_C50,_Y_Y
#+     - https://enpkg.commons-lab.org/kg/npc_Caryolane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Caryophyllane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Casbane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Cassane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Catechols_with_side_chains
#+     - https://enpkg.commons-lab.org/kg/npc_Cedrane_and_Isocedrane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Cembrane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Cephalosporins
#+     - https://enpkg.commons-lab.org/kg/npc_Cephalotaxus_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Cephamycins
#+     - https://enpkg.commons-lab.org/kg/npc_Ceramides
#+     - https://enpkg.commons-lab.org/kg/npc_Cericerane_sesterterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Chalcones
#+     - https://enpkg.commons-lab.org/kg/npc_Chamigrane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Cheilanthane_sesterterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Chiloscyphane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Cholane_steroids
#+     - https://enpkg.commons-lab.org/kg/npc_Cholestane_steroids
#+     - https://enpkg.commons-lab.org/kg/npc_Chromones
#+     - https://enpkg.commons-lab.org/kg/npc_Cinnamic_acid_amides
#+     - https://enpkg.commons-lab.org/kg/npc_Cinnamic_acids_and_derivatives
#+     - https://enpkg.commons-lab.org/kg/npc_Cinnamoyl_phenols
#+     - https://enpkg.commons-lab.org/kg/npc_Clavams
#+     - https://enpkg.commons-lab.org/kg/npc_Clavulones
#+     - https://enpkg.commons-lab.org/kg/npc_Cleistanthane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Clovane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Colensane_and_Clerodane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Coloratane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Copaane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Copacamphane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Corynanthe_type
#+     - https://enpkg.commons-lab.org/kg/npc_Coumarinolignans
#+     - https://enpkg.commons-lab.org/kg/npc_Coumaronochromones
#+     - https://enpkg.commons-lab.org/kg/npc_Coumestan
#+     - https://enpkg.commons-lab.org/kg/npc_Cryptophycins
#+     - https://enpkg.commons-lab.org/kg/npc_Cubebane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Cucurbitane_triterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Cuparane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Cyano_esters
#+     - https://enpkg.commons-lab.org/kg/npc_Cyanogenic_glycosides
#+     - https://enpkg.commons-lab.org/kg/npc_Cyathane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Cyclamides
#+     - https://enpkg.commons-lab.org/kg/npc_Cyclic_peptides
#+     - https://enpkg.commons-lab.org/kg/npc_Cyclitols
#+     - https://enpkg.commons-lab.org/kg/npc_Cycloabietane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Cycloapotirucallane_triterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Cycloartane_triterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Cyclobisabolane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Cycloeudesmane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Cyclofarnesane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Cyclogermacrane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Cyclolaurane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Cyclonerane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Cyclophytane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Cyclopiane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Cyclopiazonic_acid_tpye_tetramate_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Cytochalasan_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Cytosporins
#+     - https://enpkg.commons-lab.org/kg/npc_Dammarane_and_Protostane_triterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Daphnane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Daucane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Decalins_with_2_pyrones
#+     - https://enpkg.commons-lab.org/kg/npc_Decalins_with_side_chains
#+     - https://enpkg.commons-lab.org/kg/npc_Depsides
#+     - https://enpkg.commons-lab.org/kg/npc_Depsides_and_depsidones
#+     - https://enpkg.commons-lab.org/kg/npc_Depsidones
#+     - https://enpkg.commons-lab.org/kg/npc_Depsipeptides
#+     - https://enpkg.commons-lab.org/kg/npc_Devadarane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Diacylglycerols
#+     - https://enpkg.commons-lab.org/kg/npc_Dialkylresorcinols
#+     - https://enpkg.commons-lab.org/kg/npc_Diarylether_type_diarylheptanoids
#+     - https://enpkg.commons-lab.org/kg/npc_Dibenzocyclooctadienes_lignans
#+     - https://enpkg.commons-lab.org/kg/npc_Dibenzylbutane_lignans
#+     - https://enpkg.commons-lab.org/kg/npc_Dibenzylbutyrolactone_lignans
#+     - https://enpkg.commons-lab.org/kg/npc_Dicarboxylic_acids
#+     - https://enpkg.commons-lab.org/kg/npc_Dihydroflavonols
#+     - https://enpkg.commons-lab.org/kg/npc_Dimeric_phloroglucinols
#+     - https://enpkg.commons-lab.org/kg/npc_Dipeptides
#+     - https://enpkg.commons-lab.org/kg/npc_Disaccharides
#+     - https://enpkg.commons-lab.org/kg/npc_Dolabellane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Dolastane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Dolichols
#+     - https://enpkg.commons-lab.org/kg/npc_Drimane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Duclauxin_and_derivatives
#+     - https://enpkg.commons-lab.org/kg/npc_Dunniane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Ecdysteroids
#+     - https://enpkg.commons-lab.org/kg/npc_Elemane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Elfamycins
#+     - https://enpkg.commons-lab.org/kg/npc_Enediynes
#+     - https://enpkg.commons-lab.org/kg/npc_Epothilones
#+     - https://enpkg.commons-lab.org/kg/npc_Epoxy_fatty_acids
#+     - https://enpkg.commons-lab.org/kg/npc_Epoxyeicosatrienoic_acids
#+     - https://enpkg.commons-lab.org/kg/npc_Eremane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Eremophilane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Ergostane_steroids
#+     - https://enpkg.commons-lab.org/kg/npc_Ergot_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Ericamycins
#+     - https://enpkg.commons-lab.org/kg/npc_Erythromycins
#+     - https://enpkg.commons-lab.org/kg/npc_Erythroxylane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Estrane_steroids
#+     - https://enpkg.commons-lab.org/kg/npc_Eudesmane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Eunicellane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Farnesane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Fasamycins_and_derivatives
#+     - https://enpkg.commons-lab.org/kg/npc_Fatty_acid_estolides
#+     - https://enpkg.commons-lab.org/kg/npc_Fatty_acyl_CoAs
#+     - https://enpkg.commons-lab.org/kg/npc_Fatty_acyl_carnitines
#+     - https://enpkg.commons-lab.org/kg/npc_Fatty_acyl_glycosides_of_mono__and_disaccharides
#+     - https://enpkg.commons-lab.org/kg/npc_Fatty_acyl_homoserine_lactones
#+     - https://enpkg.commons-lab.org/kg/npc_Fatty_alcohols
#+     - https://enpkg.commons-lab.org/kg/npc_Fatty_aldehydes
#+     - https://enpkg.commons-lab.org/kg/npc_Fatty_ethers
#+     - https://enpkg.commons-lab.org/kg/npc_Fatty_nitriles
#+     - https://enpkg.commons-lab.org/kg/npc_Fenchane_monoterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Fernane_and_Arborinane_triterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Filicane_triterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Flavan_3_ols
#+     - https://enpkg.commons-lab.org/kg/npc_Flavandiols_Leucoanthocyanidins
#+     - https://enpkg.commons-lab.org/kg/npc_Flavanones
#+     - https://enpkg.commons-lab.org/kg/npc_Flavans
#+     - https://enpkg.commons-lab.org/kg/npc_Flavones
#+     - https://enpkg.commons-lab.org/kg/npc_Flavonolignans
#+     - https://enpkg.commons-lab.org/kg/npc_Flavonols
#+     - https://enpkg.commons-lab.org/kg/npc_Flavonostilbenes
#+     - https://enpkg.commons-lab.org/kg/npc_Friedelane_triterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Fukinane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Fungal_DPEs
#+     - https://enpkg.commons-lab.org/kg/npc_Fungal_cyclic_polyketides_Miscellaneous
#+     - https://enpkg.commons-lab.org/kg/npc_Furanoabietane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Furanoid_lignans
#+     - https://enpkg.commons-lab.org/kg/npc_Furans
#+     - https://enpkg.commons-lab.org/kg/npc_Furocoumarins
#+     - https://enpkg.commons-lab.org/kg/npc_Furofuranoid_lignans
#+     - https://enpkg.commons-lab.org/kg/npc_Furostane_steroids
#+     - https://enpkg.commons-lab.org/kg/npc_Fusicoccane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Fusidane_triterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Gallotannins
#+     - https://enpkg.commons-lab.org/kg/npc_Gammacerane_triterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Germacrane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Gibberellins
#+     - https://enpkg.commons-lab.org/kg/npc_Glucosinolates
#+     - https://enpkg.commons-lab.org/kg/npc_Glutinane_triterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Glycerophosphates
#+     - https://enpkg.commons-lab.org/kg/npc_Glycerophosphocholines
#+     - https://enpkg.commons-lab.org/kg/npc_Glycerophosphoethanolamines
#+     - https://enpkg.commons-lab.org/kg/npc_Glycerophosphoglycerols
#+     - https://enpkg.commons-lab.org/kg/npc_Glycerophosphoglycerophosphates
#+     - https://enpkg.commons-lab.org/kg/npc_Glycerophosphoinositol_phosphates
#+     - https://enpkg.commons-lab.org/kg/npc_Glycerophosphoinositolglycans
#+     - https://enpkg.commons-lab.org/kg/npc_Glycerophosphoinositols
#+     - https://enpkg.commons-lab.org/kg/npc_Glycerophosphoserines
#+     - https://enpkg.commons-lab.org/kg/npc_Glycosyldiacylglycerols
#+     - https://enpkg.commons-lab.org/kg/npc_Glycosylmonoacylglycerols
#+     - https://enpkg.commons-lab.org/kg/npc_Gorgonane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Grayanotoxane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Griseofulvins
#+     - https://enpkg.commons-lab.org/kg/npc_Guaiane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Guanacastane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Gymnomitrane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Halimane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Halogenated_hydrocarbons
#+     - https://enpkg.commons-lab.org/kg/npc_Hamigerane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Hapalindole_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Hasubanan_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Hepoxilins
#+     - https://enpkg.commons-lab.org/kg/npc_Herbertane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Heterocyclic_fatty_acids
#+     - https://enpkg.commons-lab.org/kg/npc_Himachalane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Hirsutane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Homoerythrina_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Homofarnesane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Hopane_and_Moretane_triterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Humbertiane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Humulane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Hydrocarbons
#+     - https://enpkg.commons-lab.org/kg/npc_Hydroperoxy_fatty_acids
#+     - https://enpkg.commons-lab.org/kg/npc_Hydroxy_fatty_acids
#+     - https://enpkg.commons-lab.org/kg/npc_Hydroxy_hydroperoxyeicosapentaenoic_acids
#+     - https://enpkg.commons-lab.org/kg/npc_Hydroxy_hydroperoxyeicosatetraenoic_acids
#+     - https://enpkg.commons-lab.org/kg/npc_Hydroxy_hydroperoxyeicosatrienoic_acids
#+     - https://enpkg.commons-lab.org/kg/npc_Iboga_type
#+     - https://enpkg.commons-lab.org/kg/npc_Icetexane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Illudalane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Illudane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Imidazole_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Indole_Diterpenoid_alkaloids_Penitrems
#+     - https://enpkg.commons-lab.org/kg/npc_Indole_diketopiperazine_alkaloids_L_Trp,_L_Ala
#+     - https://enpkg.commons-lab.org/kg/npc_Indole_diketopiperazine_alkaloids_L_Trp,_L_Pro
#+     - https://enpkg.commons-lab.org/kg/npc_Indole_diketopiperazine_alkaloids_L_Trp,_L_Trp
#+     - https://enpkg.commons-lab.org/kg/npc_Indolizidine_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Ingenane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Iphionane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Iridoids_monoterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Irregular_monoterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Isariotin_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Ishwarane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Isoaurones
#+     - https://enpkg.commons-lab.org/kg/npc_Isocomane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Isocoumarins
#+     - https://enpkg.commons-lab.org/kg/npc_Isodaucane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Isoflavanones
#+     - https://enpkg.commons-lab.org/kg/npc_Isoflavones
#+     - https://enpkg.commons-lab.org/kg/npc_Isofurans
#+     - https://enpkg.commons-lab.org/kg/npc_Isoindole_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Isolactarane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Isoprostanes
#+     - https://enpkg.commons-lab.org/kg/npc_Isoquinoline_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Ivaxillarane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Jasmonic_acids
#+     - https://enpkg.commons-lab.org/kg/npc_Jatrophane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Jatropholane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Kaurane_and_Phyllocladane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Kavalactones_and_derivatives
#+     - https://enpkg.commons-lab.org/kg/npc_Kempane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Labdane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Lactam_bearing_macrolide_lactones
#+     - https://enpkg.commons-lab.org/kg/npc_Lactarane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Lactones
#+     - https://enpkg.commons-lab.org/kg/npc_Ladder_polyethers
#+     - https://enpkg.commons-lab.org/kg/npc_Lanostane,_Tirucallane_and_Euphane_triterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Lathyrane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Laurane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Leukotrienes
#+     - https://enpkg.commons-lab.org/kg/npc_Levuglandins
#+     - https://enpkg.commons-lab.org/kg/npc_Limonoids
#+     - https://enpkg.commons-lab.org/kg/npc_Linear_diarylheptanoids
#+     - https://enpkg.commons-lab.org/kg/npc_Linear_peptides
#+     - https://enpkg.commons-lab.org/kg/npc_Linear_polyenes
#+     - https://enpkg.commons-lab.org/kg/npc_Linear_sesterterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Linear_tetronates
#+     - https://enpkg.commons-lab.org/kg/npc_Lipopeptides
#+     - https://enpkg.commons-lab.org/kg/npc_Lipoxins
#+     - https://enpkg.commons-lab.org/kg/npc_Lippifoliane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Lobane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Long_Chain_Bicyclic_Phosphotriester
#+     - https://enpkg.commons-lab.org/kg/npc_Longibornane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Longifolane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Longipinane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Luminacins_and_derivatives
#+     - https://enpkg.commons-lab.org/kg/npc_Lupane_triterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Macrocyclic_tetramic_acids
#+     - https://enpkg.commons-lab.org/kg/npc_Macrolide_lactams
#+     - https://enpkg.commons-lab.org/kg/npc_Macrolide_lactones
#+     - https://enpkg.commons-lab.org/kg/npc_Macrotetrolides
#+     - https://enpkg.commons-lab.org/kg/npc_Malabaricane_triterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Marasmane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Maresins
#+     - https://enpkg.commons-lab.org/kg/npc_Megastigmanes
#+     - https://enpkg.commons-lab.org/kg/npc_Melithiazole_and_Myxothiazole_derivatives
#+     - https://enpkg.commons-lab.org/kg/npc_Menthane_monoterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Merohemiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Meromonoterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Merosesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Meroterpenoids_with_bridged_ring
#+     - https://enpkg.commons-lab.org/kg/npc_Methoxy_fatty_acids
#+     - https://enpkg.commons-lab.org/kg/npc_Methyl_xanthones
#+     - https://enpkg.commons-lab.org/kg/npc_Microcolins_and_mirabimids
#+     - https://enpkg.commons-lab.org/kg/npc_Microginins
#+     - https://enpkg.commons-lab.org/kg/npc_Minor_lignans
#+     - https://enpkg.commons-lab.org/kg/npc_Miscellaneous_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Miscellaneous_apocarotenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Miscellaneous_meroterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Miscellaneous_polyketides
#+     - https://enpkg.commons-lab.org/kg/npc_Mitomycins
#+     - https://enpkg.commons-lab.org/kg/npc_Monacolins_and_Monacolin_derivatives
#+     - https://enpkg.commons-lab.org/kg/npc_Monoacylglycerols
#+     - https://enpkg.commons-lab.org/kg/npc_Monoalkylresorcinols
#+     - https://enpkg.commons-lab.org/kg/npc_Monocarbocyclic_sesterterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Monocyclic_b_lactams
#+     - https://enpkg.commons-lab.org/kg/npc_Monocyclic_guanidine_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Monocyclic_monoterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Monomeric_stilbenes
#+     - https://enpkg.commons-lab.org/kg/npc_Monosaccharides
#+     - https://enpkg.commons-lab.org/kg/npc_Morphinan_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Mulinane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Multiflorane_triterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Mycolic_acids
#+     - https://enpkg.commons-lab.org/kg/npc_Mycosporine_and_Mycosporine_like_amino_acids
#+     - https://enpkg.commons-lab.org/kg/npc_Myrsinane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_N_acyl_amines
#+     - https://enpkg.commons-lab.org/kg/npc_N_acyl_ethanolamines_endocannabinoids
#+     - https://enpkg.commons-lab.org/kg/npc_Nagilactone_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Naphthalenes_and_derivatives
#+     - https://enpkg.commons-lab.org/kg/npc_Naphthalenones
#+     - https://enpkg.commons-lab.org/kg/npc_Naphthoquinones
#+     - https://enpkg.commons-lab.org/kg/npc_Nardosinane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Neoflavonoids
#+     - https://enpkg.commons-lab.org/kg/npc_Neohopane_triterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Neolignans
#+     - https://enpkg.commons-lab.org/kg/npc_Neurofurans
#+     - https://enpkg.commons-lab.org/kg/npc_Neuroprostanes
#+     - https://enpkg.commons-lab.org/kg/npc_Neutral_glycosphingolipids
#+     - https://enpkg.commons-lab.org/kg/npc_Nitro_fatty_acids
#+     - https://enpkg.commons-lab.org/kg/npc_Nonadrides
#+     - https://enpkg.commons-lab.org/kg/npc_Norcembrane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Noreremophilane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Noreudesmane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Norkaurane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Norlabdane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Norpimarane_and_Norisopimarane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Norsesterterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Obtusane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Oleanane_triterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Oligomeric_phloroglucinols_phlorotannins
#+     - https://enpkg.commons-lab.org/kg/npc_Oligomeric_stibenes
#+     - https://enpkg.commons-lab.org/kg/npc_Oligomycins
#+     - https://enpkg.commons-lab.org/kg/npc_Onocerane_triterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Open_chain_polyketides
#+     - https://enpkg.commons-lab.org/kg/npc_Open_chained_neoflavonoids
#+     - https://enpkg.commons-lab.org/kg/npc_Ophiobolane_sesterterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Oplopane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Oppositane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Other_Docosanoids
#+     - https://enpkg.commons-lab.org/kg/npc_Other_Eicosanoids
#+     - https://enpkg.commons-lab.org/kg/npc_Other_Octadecanoids
#+     - https://enpkg.commons-lab.org/kg/npc_Other_indole_diketopiperazine_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Other_polyketide_meroterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Oxa_Bridged_Macrolides
#+     - https://enpkg.commons-lab.org/kg/npc_Oxasqualenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Oxazole_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Oxidized_glycerophospholipids
#+     - https://enpkg.commons-lab.org/kg/npc_Oxo_fatty_acids
#+     - https://enpkg.commons-lab.org/kg/npc_Oxygenated_hydrocarbons
#+     - https://enpkg.commons-lab.org/kg/npc_Pachydictyane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Pachysanane_triterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Pacifigorgiane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Paraconic_acids_and_derivatives
#+     - https://enpkg.commons-lab.org/kg/npc_Paraliane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Parguerane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Patchoulane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Paulomycins_and_derivatives
#+     - https://enpkg.commons-lab.org/kg/npc_Penicillins
#+     - https://enpkg.commons-lab.org/kg/npc_Pentacyclic_guanidine_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Pentalenane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Pepluane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Peptaibols
#+     - https://enpkg.commons-lab.org/kg/npc_Perforane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Phenalens
#+     - https://enpkg.commons-lab.org/kg/npc_Phenanthrenes
#+     - https://enpkg.commons-lab.org/kg/npc_Phenazine_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Phenethylisoquinoline_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Phenoxazine_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Phenylalanine_derived_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Phenylethanoids
#+     - https://enpkg.commons-lab.org/kg/npc_Phenylethylamines
#+     - https://enpkg.commons-lab.org/kg/npc_Phloroglucinol_terpene_hybrids
#+     - https://enpkg.commons-lab.org/kg/npc_Phoslactomycins_or_Phosphazomycins
#+     - https://enpkg.commons-lab.org/kg/npc_Phosphosphingolipids
#+     - https://enpkg.commons-lab.org/kg/npc_Phthalide_derivatives
#+     - https://enpkg.commons-lab.org/kg/npc_Phytane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Phytofurans
#+     - https://enpkg.commons-lab.org/kg/npc_Phytoprostanes
#+     - https://enpkg.commons-lab.org/kg/npc_Picrotoxane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Pimarane_and_Isopimarane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Pinane_monoterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Pinguisane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Piperidine_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Plant_xanthones
#+     - https://enpkg.commons-lab.org/kg/npc_Platensimycin_and_Platencins
#+     - https://enpkg.commons-lab.org/kg/npc_Podocarpane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Polyamines
#+     - https://enpkg.commons-lab.org/kg/npc_Polyene_macrolides
#+     - https://enpkg.commons-lab.org/kg/npc_Polyesters
#+     - https://enpkg.commons-lab.org/kg/npc_Polyether_ionophores
#+     - https://enpkg.commons-lab.org/kg/npc_Polypodane_triterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Polyprenol_derivatives
#+     - https://enpkg.commons-lab.org/kg/npc_Polyprenylated_cyclic_polyketides_Hop_meroterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Polysaccharides
#+     - https://enpkg.commons-lab.org/kg/npc_Pradimicins
#+     - https://enpkg.commons-lab.org/kg/npc_Pregnane_steroids
#+     - https://enpkg.commons-lab.org/kg/npc_Premyrsinane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Prenyl_quinone_meroterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Prenylated,geranylated_phloroglucinols
#+     - https://enpkg.commons-lab.org/kg/npc_Prenylbisabolane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Prenyleudesmane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Presilphiperfolane_and_Probotryane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Prezizaane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Primary_amides
#+     - https://enpkg.commons-lab.org/kg/npc_Proanthocyanins
#+     - https://enpkg.commons-lab.org/kg/npc_Prodigiosins
#+     - https://enpkg.commons-lab.org/kg/npc_Prostaglandins
#+     - https://enpkg.commons-lab.org/kg/npc_Protoberberine_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Protoilludane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Protopine_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Pseudoguaiane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Pseudopterane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Pterocarpan
#+     - https://enpkg.commons-lab.org/kg/npc_Pulvinones
#+     - https://enpkg.commons-lab.org/kg/npc_Purine_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Purine_nucleosides
#+     - https://enpkg.commons-lab.org/kg/npc_Purine_nucleostides
#+     - https://enpkg.commons-lab.org/kg/npc_Purine_nucleotides
#+     - https://enpkg.commons-lab.org/kg/npc_Pyranocoumarins
#+     - https://enpkg.commons-lab.org/kg/npc_Pyrazine_and_Piperazine_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Pyridine_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Pyrimidine_nucleosides
#+     - https://enpkg.commons-lab.org/kg/npc_Pyrimidine_nucleostides
#+     - https://enpkg.commons-lab.org/kg/npc_Pyrimidine_nucleotides
#+     - https://enpkg.commons-lab.org/kg/npc_Pyrrocidine_tetramate_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Pyrrole_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Pyrrolidine_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Pyrrolizidine_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Pyrroloindole_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Pyrroloquinoline_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Quadrane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Quassinoids
#+     - https://enpkg.commons-lab.org/kg/npc_Quinazoline_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Quinoline_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Quinolizidine_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Resin_glycosides
#+     - https://enpkg.commons-lab.org/kg/npc_Resolvin_Ds
#+     - https://enpkg.commons-lab.org/kg/npc_Resolvin_Es
#+     - https://enpkg.commons-lab.org/kg/npc_Rhamnofolane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Rhamnolipids
#+     - https://enpkg.commons-lab.org/kg/npc_Rhizoxins
#+     - https://enpkg.commons-lab.org/kg/npc_RiPPs
#+     - https://enpkg.commons-lab.org/kg/npc_RiPPs_Amatoxins_and_Phallotoxins
#+     - https://enpkg.commons-lab.org/kg/npc_RiPPs_Cyanobactins
#+     - https://enpkg.commons-lab.org/kg/npc_RiPPs_Lanthipeptides
#+     - https://enpkg.commons-lab.org/kg/npc_RiPPs_Thiopeptides
#+     - https://enpkg.commons-lab.org/kg/npc_Rotenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Rotundane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Sacculatane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Salinosporamides
#+     - https://enpkg.commons-lab.org/kg/npc_Santalane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Saponaceolide_triterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Sativane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Saxitoxins
#+     - https://enpkg.commons-lab.org/kg/npc_Scalarane_sesterterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Secoabietane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Secoeudesmane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Secogermacrane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Secoiridoid_monoterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Secokaurane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Secolabdane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Segetane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Selaginellins
#+     - https://enpkg.commons-lab.org/kg/npc_Serratane_triterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Serrulatane_and_Biflorane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Shikimic_acids_and_derivatives
#+     - https://enpkg.commons-lab.org/kg/npc_Shionane_triterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Silphinane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Silphiperfolane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Simple_amide_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Simple_aromatic_polyketides
#+     - https://enpkg.commons-lab.org/kg/npc_Simple_coumarins
#+     - https://enpkg.commons-lab.org/kg/npc_Simple_cyclic_polyketides
#+     - https://enpkg.commons-lab.org/kg/npc_Simple_diketopiperazine_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Simple_indole_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Simple_oxindole_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Simple_phenolic_acids
#+     - https://enpkg.commons-lab.org/kg/npc_Simple_tetramate_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Sinularane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Sophorolipids
#+     - https://enpkg.commons-lab.org/kg/npc_Sorbicilinoids
#+     - https://enpkg.commons-lab.org/kg/npc_Sphaerane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Sphaeroane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Sphenolobane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Sphingoid_bases
#+     - https://enpkg.commons-lab.org/kg/npc_Spiroaxane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Spirodioxynaphthalenes
#+     - https://enpkg.commons-lab.org/kg/npc_Spirostane_steroids
#+     - https://enpkg.commons-lab.org/kg/npc_Spirotetronate_macrolides
#+     - https://enpkg.commons-lab.org/kg/npc_Spirovetivane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Spongiane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Spriromeroterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Stemona_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Steroidal_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Sterpurane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Stictane_triterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Stigmastane_steroids
#+     - https://enpkg.commons-lab.org/kg/npc_Stilbenolignans
#+     - https://enpkg.commons-lab.org/kg/npc_Straight_chain_fatty_acids
#+     - https://enpkg.commons-lab.org/kg/npc_Streptogramins
#+     - https://enpkg.commons-lab.org/kg/npc_Streptothricins_and_derivatives
#+     - https://enpkg.commons-lab.org/kg/npc_Strobilurins_and_derivatives
#+     - https://enpkg.commons-lab.org/kg/npc_Strychnos_type
#+     - https://enpkg.commons-lab.org/kg/npc_Tantazoles_and_mirabazoles
#+     - https://enpkg.commons-lab.org/kg/npc_Taraxerane_triterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Taxane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Terpenoid_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Terpenoid_tetrahydroisoquinoline_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Tetracyclic_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Tetracyclines
#+     - https://enpkg.commons-lab.org/kg/npc_Tetrahydroisoquinoline_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Tetraketide_meroterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Tetrodotoxins
#+     - https://enpkg.commons-lab.org/kg/npc_Thapsane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Thia_fatty_acids
#+     - https://enpkg.commons-lab.org/kg/npc_Thiazole_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Thiodiketopiperazine_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Thromboxanes
#+     - https://enpkg.commons-lab.org/kg/npc_Thujane_monoterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Thujopsane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Tigliane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Totarane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Trachylobane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Tremulane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Triacylglycerols
#+     - https://enpkg.commons-lab.org/kg/npc_Trichothecane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Tricyclic_guanidine_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Triketide_meroterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Trinervitane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Tripeptides
#+     - https://enpkg.commons-lab.org/kg/npc_Tropane_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Tropolones_and_derivatives_PKS
#+     - https://enpkg.commons-lab.org/kg/npc_Tropolones_and_derivatives_Shikimate
#+     - https://enpkg.commons-lab.org/kg/npc_Tylosins
#+     - https://enpkg.commons-lab.org/kg/npc_Unknown
#+     - https://enpkg.commons-lab.org/kg/npc_Unsaturated_fatty_acids
#+     - https://enpkg.commons-lab.org/kg/npc_Ursane_and_Taraxastane_triterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Usnic_acid_and_derivatives
#+     - https://enpkg.commons-lab.org/kg/npc_Valerane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Valerenane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Valparane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Verrucosane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Verticillane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Villanovane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Viscidane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Vitamin_D2_and_derivatives
#+     - https://enpkg.commons-lab.org/kg/npc_Vitamin_D3_and_derivatives
#+     - https://enpkg.commons-lab.org/kg/npc_Wax_diesters
#+     - https://enpkg.commons-lab.org/kg/npc_Wax_monoesters
#+     - https://enpkg.commons-lab.org/kg/npc_Xeniaphyllane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Xenicane_diterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_Yohimbine_like_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_Zearalenones
#+     - https://enpkg.commons-lab.org/kg/npc_Zizaane_sesquiterpenoids
#+     - https://enpkg.commons-lab.org/kg/npc_m_Terphenyls
#+     - https://enpkg.commons-lab.org/kg/npc_p_Terphenyls
#+     - https://enpkg.commons-lab.org/kg/npc_pteridine_alkaloids
#+     - https://enpkg.commons-lab.org/kg/npc_unknown

PREFIX enpkg: <https://enpkg.commons-lab.org/kg/>
PREFIX enpkgmodule: <https://enpkg.commons-lab.org/module/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>

SELECT ?extract ?organe ?species_name ?genus_name ?family_name ?count_of_selected_class
WHERE
    {  
    ?material enpkg:has_lab_process ?extract .
        ?material enpkgmodule:has_organe ?organe .
        ?material enpkg:has_wd_id ?wd_sp .
        OPTIONAL
        {
            SERVICE <https://query.wikidata.org/sparql> {
            ?wd_sp wdt:P225 ?species_name .
            ?family wdt:P31 wd:Q16521 ;
                wdt:P105 wd:Q35409 ;
                wdt:P225 ?family_name ;
                ^wdt:P171* ?wd_sp .
            ?genus wdt:P31 wd:Q16521 ;
                wdt:P105 wd:Q34740 ;
                wdt:P225 ?genus_name ;
                ^wdt:P171* ?wd_sp 
            }
        }
        {
            SELECT ?extract (COUNT(DISTINCT ?feature) AS ?count_of_selected_class)
            WHERE
            {   
                ?extract rdf:type enpkg:LabExtract .
                    ?extract enpkg:has_LCMS ?lcms .
                        ?lcms rdf:type enpkg:LCMSAnalysisPos .
                        ?lcms enpkg:has_lcms_feature_list ?feature_list .
                            ?feature_list enpkg:has_lcms_feature ?feature .
                                ?feature enpkg:has_canopus_annotation ?canopus .
                                    ?canopus enpkg:has_canopus_npc_class ?_NPCClass_iri .
                                    ?canopus enpkg:has_canopus_npc_class_prob ?class_prob .
                                    FILTER((?class_prob > 0.5)) .
            } GROUP BY ?extract ORDER BY DESC(?count_of_selected_class)
        }
    }
