#+ summary: List all NPC classes
#+ description: List all NPC classes
#+ endpoint: https://enpkg.commons-lab.org/graphdb/repositories/ENPKG
#+ tags:
#+   - ENPKG


PREFIX enpkg: <https://enpkg.commons-lab.org/kg/>

SELECT DISTINCT ?npc_class
WHERE
    { 
    ?npc_class rdf:type enpkg:NPCClass
    }
