#+ summary: Get the PI mode LCMS features with SIRIUS annotation for which a LCMS feature in NI mode of the same extract is annotated with the same IK2D and has the same RT.
#+ description: Get the PI mode LCMS features with SIRIUS annotation for which a LCMS feature in NI mode of the same extract is annotated with the same IK2D and has the same RT.
#+ endpoint: https://enpkg.commons-lab.org/graphdb/repositories/ENPKG
#+ tags:
#+   - ENPKG
#+   - Templated
#+ defaults:
#+   - RTTolerance: 5
#+ enumerate:
#+   - SampleCode:
#+     - VGF156_A01
#+     - VGF156_A02
#+     - VGF156_A03
#+     - VGF156_A04
#+     - VGF156_A05
#+     - VGF156_A06
#+     - VGF156_A07
#+     - VGF156_A08
#+     - VGF156_A09
#+     - VGF156_A10
#+     - VGF156_A11
#+     - VGF156_A12
#+     - VGF156_B01
#+     - VGF156_B02
#+     - VGF156_B03
#+     - VGF156_B04
#+     - VGF156_B05
#+     - VGF156_B06
#+     - VGF156_B07
#+     - VGF156_B08
#+     - VGF156_B09
#+     - VGF156_B10
#+     - VGF156_B11
#+     - VGF156_B12
#+     - VGF156_C01
#+     - VGF156_C02
#+     - VGF156_C03
#+     - VGF156_C04
#+     - VGF156_C05
#+     - VGF156_C06
#+     - VGF156_C07
#+     - VGF156_C08
#+     - VGF156_C09
#+     - VGF156_C10
#+     - VGF156_C11
#+     - VGF156_C12
#+     - VGF156_D01
#+     - VGF156_D02
#+     - VGF156_D03
#+     - VGF156_D04
#+     - VGF156_D05
#+     - VGF156_D06
#+     - VGF156_D07
#+     - VGF156_D08
#+     - VGF156_D09
#+     - VGF156_D10
#+     - VGF156_D11
#+     - VGF156_D12
#+     - VGF156_E01
#+     - VGF156_E02
#+     - VGF156_E03
#+     - VGF156_E04
#+     - VGF156_E05
#+     - VGF156_E06
#+     - VGF156_E07
#+     - VGF156_E08
#+     - VGF156_E09
#+     - VGF156_E10
#+     - VGF156_E11
#+     - VGF156_E12
#+     - VGF156_F01
#+     - VGF156_F02
#+     - VGF156_F03
#+     - VGF156_F04
#+     - VGF156_F05
#+     - VGF156_F06
#+     - VGF156_F07
#+     - VGF156_F08
#+     - VGF156_F09
#+     - VGF156_F10
#+     - VGF156_F11
#+     - VGF156_F12
#+     - VGF156_G01
#+     - VGF156_G02
#+     - VGF156_G03
#+     - VGF156_G04
#+     - VGF156_G05
#+     - VGF156_G06
#+     - VGF156_G07
#+     - VGF156_G08
#+     - VGF156_G09
#+     - VGF156_G10
#+     - VGF156_G11
#+     - VGF156_G12
#+     - VGF156_H01
#+     - VGF156_H02
#+     - VGF156_H03
#+     - VGF156_H04
#+     - VGF156_H05
#+     - VGF156_H06
#+     - VGF156_H07
#+     - VGF156_H08
#+     - VGF156_H09
#+     - VGF156_H10
#+     - VGF156_H11
#+     - VGF156_H12

PREFIX enpkg: <https://enpkg.commons-lab.org/kg/>
PREFIX enpkgmodule: <https://enpkg.commons-lab.org/module/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
            
SELECT DISTINCT ?feature ?feature_opp ?ik2d ?rt ?rt_opp
WHERE
{    
    {
    ?sample rdf:type enpkg:LabExtract
    FILTER(regex(str(?sample), ?_SampleCode))

    ?sample enpkg:has_LCMS ?lcms .
        ?lcms rdf:type enpkg:LCMSAnalysisPos .
        ?lcms enpkg:has_lcms_feature_list ?feature_list .
            ?feature_list enpkg:has_lcms_feature ?feature .                    
                ?feature enpkg:has_retention_time ?rt .
                ?feature enpkg:has_sirius_annotation ?sirius .
                    ?sirius enpkg:has_InChIkey2D ?ik2d .
                    
        
    ?sample enpkg:has_LCMS ?lcms_opp .
    ?lcms_opp rdf:type enpkg:LCMSAnalysisNeg .
    ?lcms_opp enpkg:has_lcms_feature_list ?feature_list_opp .
        ?feature_list_opp enpkg:has_lcms_feature ?feature_opp .
            ?feature_opp enpkg:has_retention_time ?rt_opp .
            ?feature_opp enpkg:has_sirius_annotation ?sirius_opp .
                ?sirius_opp enpkg:has_InChIkey2D ?ik2d .

    FILTER(((?rt - ?RTTolerance_integer) < ?rt_opp) && ((?rt + ?RTTolerance_integer) > ?rt_opp))
    }
}
